/**
* AclAccountDO entity encapsulation table AclAccount record. 
* @author luyl,Generated by the auto build tools .
* @Time 2017-09-07 14:17:39
*/
package org.web.acl.domain;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class AclAccountDO {

	// 账户表主键
	private Long aclAccountId;
	// 账户名称
	private String accountName;
	// 账户工号
	private String accountNum;
	// 状态,ON OFF.
	private String accountStatus;
	// 业务线名称
	private String businessLine;
	// 账户手机号
	private String phone;
	// 账户邮箱
	private String mail;
	// 大部门
	private String firstDepartment;
	// 小部门
	private String secondDepartment;
	// 职位
	private String position;
	// 处理人
	private String inputer;
	// 记录创建时间
	private Date createTime;
	// 记录修改时间
	private Date updateTime;
	// 是否逻辑删除
	private String isDelete;
	
}


