/**
 * AclResourceDO entity encapsulation table AclResource record.
 * @author luyl,Generated by the auto build tools .
 * @Time 2017-09-11 17:08:20
 */
package org.web.acl.domain;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class AclResourceDO {

    // AclResource表主键
    private Long aclResourceId;
    // 业务线
    private String businessLine;
    // 资源名称，与resourceKey，resourceValue唯一确定一条记录
    private String resourceName;
    // 资源以KEY，MAP的方式来描述，资源KEY。
    private String resourceKey;
    // 资源以KEY，VALUE来描述，资源VALUE
    private String resourceValue;
    // 资源等级，用树状结构描述资源
    private String resourceLevel;
    // 拓展value
    private String extendsValue;
    // 描述
    private String description;
    // 资源状态
    private String resourceStatus;
    // 资源类型，扩展属性，非必入例项
    private String resourceType;
    // 第一级Level
    private String firstLevel;
    // 第二级Level
    private String secondLevel;
    // 第三级Level
    private String thirdLevel;
    // 第四级Level
    private String fourthLevel;
    // 第五级Level
    private String fifthLevel;
    // 记录操作者
    private String inputer;
    // 记录创建时间
    private Date inputTime;
    // 记录修改时间
    private Date updateTime;
    // 记录是否逻辑删除
    private String isDelete;

}

