/**
* AclResourceAccountMappingDO entity encapsulation table AclResourceAccountMapping record. 
* @author luyl,Generated by the auto build tools .
* @Time 2017-09-14 18:05:04
*/
package org.web.acl.domain;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class AclResourceAccountMappingDO {

	// 表主键
	private Long aclResourceAccountMappingId;
	// 业务线
	private String businessLine;
	// 资源表主键
	private Long aclResourceId;
	// 账户表主键
	private Long aclAccountId;
	// 账户号
	private String accountNum;
	// 记录修改人
	private String inputer;
	// 记录创建时间
	private Date createTime;
	// 记录修改时间
	private Date updateTime;
	// 记录是否逻辑删除
	private String isDelete;
	
}


