/**
* AclResourceRoleMappingDO entity encapsulation table AclResourceRoleMapping record. 
* @author luyl,Generated by the auto build tools .
* @Time 2017-09-14 18:02:40
*/
package org.web.acl.domain;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class AclResourceRoleMappingDO {

	// 表主键
	private Long aclResourceRoleMappingId;
	// AclResource表主键
	private Long aclResourceId;
	// AclRole表主键
	private Long aclRoleId;
	// 业务线
	private String businessLine;
	// 记录创建时间
	private Date createTime;
	// 记录修改时间
	private Date updateTime;
	// 记录是否逻辑删除
	private String isDelete;
	// 记录修改人
	private String inputer;
	
}


