/**
* AclRoleDO entity encapsulation table AclRole record. 
* @author luyl,Generated by the auto build tools .
* @Time 2017-09-06 16:28:02
*/
package org.web.acl.domain;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class AclRoleDO {

	// ACL表主键
	private Long aclRoleId;
	// 角色分组
	private String roleGroup;
	// 角色名称
	private String roleName;
	// 角色描述
	private String description;
	// 角色所属业务线
	private String businessLine;
	// 记录修改者
	private String inputer;
	// 记录创建时间
	private Date createTime;
	// 记录修改时间
	private Date updateTime;
	// 记录是否逻辑删除
	private String isDelete;
	
}


