/**
* SessionAccountDO entity encapsulation table SessionAccount record. 
* @author luyl,Generated by the auto build tools .
* @Time 2017-09-04 18:38:51
*/
package org.web.acl.domain;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class SessionAccountDO {

	// 主键
	private Long sessionAcountId;
	// 登陆账户名称
	private String accountName;
	// 登陆账户ID
	private String accountNum;
	// 密码
	private String password;
	// 记录是否逻辑删除
	private String isDelete;
	
}


